// 데모용 샘플 문항
export const DEMO_ITEMS = [
  {
    id: 'DEMO-MATH-001',
    subject: 'math' as const,
    area: 'math.수와연산',
    gradeBand: ['ES56'],
    conceptTag: ['분수연산'],
    stem: { type: 'text' as const, payload: '3/4 + 1/2 = ?' },
    choices: [
      { id: 'a', label: '5/4' },
      { id: 'b', label: '4/6' },
      { id: 'c', label: '5/6' },
      { id: 'd', label: '1' },
    ],
    answer: { kind: 'mcq' as const, value: 'a' },
    hints: ['분모를 4로 통일하세요', '1/2 = 2/4'],
    difficulty: 3,
  },
  {
    id: 'DEMO-ENG-001',
    subject: 'english' as const,
    area: 'english.listening',
    gradeBand: ['MS1'],
    conceptTag: ['현재시제'],
    stem: { type: 'audio' as const, payload: 'She plays the piano.' },
    choices: [
      { id: 'a', label: 'She plays the piano.' },
      { id: 'b', label: 'She played the piano.' },
      { id: 'c', label: 'She will play the piano.' },
    ],
    answer: { kind: 'mcq' as const, value: 'a' },
    hints: ['현재형 동사를 찾으세요'],
    difficulty: 2,
  },
  {
    id: 'DEMO-SCI-001',
    subject: 'science' as const,
    area: 'science.물질',
    gradeBand: ['ES56'],
    conceptTag: ['상변화'],
    stem: { type: 'text' as const, payload: '물이 얼 때 일어나는 변화는?' },
    choices: [
      { id: 'a', label: '액체 → 고체' },
      { id: 'b', label: '고체 → 액체' },
      { id: 'c', label: '액체 → 기체' },
    ],
    answer: { kind: 'mcq' as const, value: 'a' },
    hints: ['얼음은 고체입니다'],
    difficulty: 2,
  },
  {
    id: 'DEMO-SOC-001',
    subject: 'social' as const,
    area: 'social.지리',
    gradeBand: ['MS1'],
    conceptTag: ['한반도지리'],
    stem: { type: 'text' as const, payload: '한국의 수도는?' },
    choices: [
      { id: 'a', label: '서울' },
      { id: 'b', label: '부산' },
      { id: 'c', label: '인천' },
    ],
    answer: { kind: 'mcq' as const, value: 'a' },
    hints: ['대한민국의 중심 도시'],
    difficulty: 1,
  },
];

